### ISSUE TITLE
[BUG] Hilbert's hotel analyzer is invisible

### ISSUE THREAD

**Issue by KubeRoot** [SinguloStation13/SinguloStation13-Archived#56]
## Testmerges:
https://github.com/SinguloStation13/SinguloStation13/pull/37

## Reproduction:

Find Hilbert's Hotel, right-click or alt-click on the table where the analyzer should be. The analyzer is there, but has a fully transparent sprite. It can still be picked up and used via right-clicking/alt-clicking. Need to look into why the sprite isn't there.

**Comment by Urumasi** [comment]
a Whitesands change to the analyzer sprite broke the subtype hilbert's analyzer, where it can't find the icon in `whitesands/icons/obj/tools.dmi` since it's in the older file `icons/obj/device.dmi`
