### ISSUE TITLE
[BUG] Recycler recycles sources of light

### ISSUE THREAD

**Issue by Laboredih123** [SinguloStation13/SinguloStation13-Archived#65]
## Reproduction:
Look at the recycler with the hardsuit light on. It eats the light while producing a denied sound effect. The hardsuit loses its ability to make light.

**Comment by Laboredih123** [comment]
You must remove and reequip the hardsuit to gain the light back, not everyone can do this however in certain situations.

**Comment by Laboredih123** [comment]
And that only works sometimes.

**Comment by KubeRoot** [comment]
That's weird, in my case the light reappeared as soon as I turn around so I was no longer facing the recycler.
Also worth noting, if you close a locker where a hardsuit light is, the light will also disappear until you move.

**Comment by Urumasi** [comment]
> 
> 
> That's weird, in my case the light reappeared as soon as I turn around so I was no longer facing the recycler.
> Also worth noting, if you close a locker where a hardsuit light is, the light will also disappear until you move.

While testing the light did not reappear after I turned around or moved
